@startuml

class "::items::Abc5" as item_0
class "::items::Abc4" as item_1
class "::items::Abc3" as item_2
class "::items::Abc2" as item_3
class "::items::Abc1" as item_4

' ::items::Abc5 --|> ::items::Abc4
item_0 --|> item_1: "priv"
' ::items::Abc4 --|> ::items::Abc3
item_1 --|> item_2: "pub"
' ::items::Abc3 --|> ::items::Abc2
item_2 --|> item_3: "prot"
' ::items::Abc2 --|> ::items::Abc1
item_3 --|> item_4: "priv"

@enduml
