@startuml

class "::Abc4B" as item_0
class "::Abc2" as item_1
class "::items::Abc1" as item_2
class "::Abc4A" as item_3

' ::Abc4B -> ::Abc2
item_0 --|> item_1: "virt pub"
' ::Abc4B -> ::items::Abc1
item_0 --|> item_2: "priv"
' ::Abc4A -> ::Abc2
item_3 --|> item_1: "pub"
' ::Abc4A -> ::items::Abc1
item_3 --|> item_2: "priv"

@enduml
