@startuml

class "::Abc4A" as item_0
class "::items::Abc3" as item_1
class "::items::Abc2" as item_2
class "::items::Abc1" as item_3

' ::Abc4A --|> ::items::Abc3
item_0 --|> item_1: "prot"
' ::Abc4A --|> ::items::Abc2
item_0 --|> item_2: "pub"
' ::Abc4A --|> ::items::Abc1
item_0 --|> item_3: "priv"

@enduml
