@startuml

card "::main() -> int" {
    :char const * bad_char = (&0xFF20);
    :uint8_t[] bad_char_array = 0xFF41FF;
    #lightgreen:return 0;
    stop
    -[hidden]->
}

card "::std::__is_constant_evaluated() -> bool" {
    #lightgreen:return 0;
    stop
    -[hidden]->
}

card "::std::__terminate() -> void" {
    :::std::terminate();
    -[hidden]->
}


@enduml
