@startuml

card "::calc_switch1() -> int" {
    start
    :timestamp = ::time(0);

partition "switch:\ntimestamp % 3" {
    ' case: 0 fallthrough: False
    if ( 0 ? ) then (yes)
        #lightgreen:return 0;
        stop
    else
    endif
}
    #lightgreen:return -3;
    stop
}

card "::calc_switch2() -> int" {
    start
    :timestamp = ::time(0);

partition "switch:\ntimestamp % 3" {
    ' case: None fallthrough: False
    if ( default ) then (yes)
        #lightgreen:return 0;
        stop
    else
        -[hidden]->
    endif
}
    #lightgreen:return -3;
    stop
}

card "::calc_switch3() -> int" {
    start
    :timestamp = ::time(0);

partition "switch:\ntimestamp % 3" {
    ' case: None fallthrough: True
    if ( default ) then (yes)
        :timestamp = ::time(0);
    else
        -[hidden]->
    endif
}
    #lightgreen:return -3;
    stop
}

card "::calc_switch4() -> int" {
    start
    :timestamp = ::time(0);

partition "switch:\ntimestamp % 3" {
    ' case: 0 fallthrough: False
    if ( 0 ? ) then (yes)
        #lightgreen:return 0;
        stop
    else
        ' case: 1 fallthrough: False
        if ( 1 ? ) then (yes)
            #lightgreen:return 1;
            stop
        else
            ' case: 2 fallthrough: False
            if ( 2 ? ) then (yes)
                #lightgreen:return 2;
                stop
            else
                ' case: None fallthrough: True
                if ( default ) then (yes)
                    :timestamp = ::time(0);
                else
                    -[hidden]->
                endif
            endif
        endif
    endif
}
    :timestamp = timestamp + 3;
    #lightgreen:return timestamp % 2;
    stop
}


@enduml
