@startuml

card "::main() -> int" {
    :::ExampleClass obj1;
    #lightgreen:return (&obj1)->switchExample(3);
    stop
    -[hidden]->
}

card "::ExampleClass::switchExample(int const paramA) -> int" {
    :int timestamp;
    :timestamp = ::time(0);
    if (timestamp & 1 == 0 ?) then (true)
        :timestamp = timestamp + paramA;
    else (false)
    endif

partition "switch:\ntimestamp % 3" {
    ' case: 0 fallthrough: True
    if ( 0 ? ) then (yes)
        if (timestamp != 0 ?) then (true)
            #lightgreen:return 0;
            stop
        else (false)
            #lightgreen:return 1;
            stop
        endif
    endif
    ' case: 1 fallthrough: True
    if ( 1 ? ) then (yes)
    endif
    ' case: 2 fallthrough: True
    if ( 2 ? ) then (yes)
        :timestamp = timestamp + paramA;
    endif
    ' case: None fallthrough: True
    if ( default ) then (yes)
        :timestamp = ::time(0);
    else
        -[hidden]->
    endif
}
    :timestamp = timestamp * 3;
    if (timestamp & 1 == 0 ?) then (true)
        :timestamp = timestamp + 1;
    else (false)
        :timestamp = timestamp + 2;
    endif
    #lightgreen:return timestamp % 2;
    stop
    -[hidden]->
}


@enduml
