@startuml

card "::item::funcA(::item::ExampleA * object) -> int" {
    #lightgreen:return 1;
    stop
    -[hidden]->
}

card "::item::ExampleB::methodB1(int const param) -> int" {
    :float const var1 = param * 3.2999999999999998223643161e+0;
    :float const var2 = param * 3.2999999999999998223643161e+0;
    :int const valA;
    :valA = (&objA)->methodA1();
    :int retX;
    :retX = this->methodB2(var1) * valA;
    :retX = retX + 7;
    :int retY;
    :retY = ::item::ExampleB::methodB3(12);
    #lightgreen:return retX + retY;
    stop
    -[hidden]->
}

card "::item::ExampleB::methodB3(int const val) -> int" {
    #lightgreen:return val;
    stop
    -[hidden]->
}

card "::item::ExampleB::methodB2(float const param) -> int" {
    :float const var = param * 6.5999999999999996447286321e+0;
    #lightgreen:return var;
    stop
    -[hidden]->
}

card "::item::ExampleA::__ct_base() -> void" {
    :(*this) = {};
    :__vtbl_ptr_type[] _ZTVN4item8ExampleAE = {[0] = 0, [1] = (&_ZTIN4item8ExampleAE), [2] = (&::item::ExampleA::__dt_comp), [3] = (&::item::ExampleA::__dt_del), [4] = (&::item::ExampleA::methodA1)};
    :_vptr.ExampleA = (&_ZTVN4item8ExampleAE) + 16;
    :fieldA = 5;
    -[hidden]->
}

card "::item::ExampleA::__ct_comp() -> void" {
    -[hidden]->
}

card "::item::ExampleA::__dt_base() -> void" {
    :__vtbl_ptr_type[] _ZTVN4item8ExampleAE = {[0] = 0, [1] = (&_ZTIN4item8ExampleAE), [2] = (&::item::ExampleA::__dt_comp), [3] = (&::item::ExampleA::__dt_del), [4] = (&::item::ExampleA::methodA1)};
    :_vptr.ExampleA = (&_ZTVN4item8ExampleAE) + 16;
    group try
        :None;
    end group

    group finally
        :(*this) = {};
    end group

    -[hidden]->
}

card "::item::ExampleA::__dt_comp() -> void" {
    -[hidden]->
}

card "::item::ExampleA::__dt_del() -> void" {
    group try
        :this->__dt_comp();
    end group

    group finally
        :::[--no entry--](this, 16);
    end group

    -[hidden]->
}

card "::item::ExampleA::methodA1() -> int" {
    :int ret = 5;
    :::item::EmptyExamle emptyObj;
    :int __tmp_906 = ::item::funcA(this);
    :ret = ret + __tmp_906;
    #lightgreen:return ret;
    stop
    -[hidden]->
}


@enduml
