@startuml

card "::funcA() -> void" {
    :::item::ExampleB objB = {[::item::ExampleA] = {[::item::ExampleA::_vptr.ExampleA] = (&_ZTVN4item8ExampleBE) + 16}};
    :::item::ExampleA * ptrA = (&objB);
    :ptrA->methodB2();
    :ptrA->methodB1();
    -[hidden]->
}

card "::item::ExampleA::methodB1() -> void" {
    -[hidden]->
}

card "::item::ExampleB::methodB1() -> void" {
    -[hidden]->
}

card "::item::ExampleA::methodB2() -> void" {
    -[hidden]->
}

card "::item::ExampleB::methodB2() -> void" {
    -[hidden]->
}

card "::item::ExampleB::__ct() -> void" {
    :(&(*this))->__ct_base();
    :_vptr.ExampleA = (&_ZTVN4item8ExampleBE) + 16;
    -[hidden]->
}

card "::item::ExampleA::__ct() -> void" {
    :_vptr.ExampleA = (&_ZTVN4item8ExampleAE) + 16;
    -[hidden]->
}

card "::item::ExampleB::__ct_base() -> void" {
    :(&(*this))->__ct_base();
    :_vptr.ExampleA = (&_ZTVN4item8ExampleBE) + 16;
    -[hidden]->
}

card "::item::ExampleA::__ct_base() -> void" {
    :_vptr.ExampleA = (&_ZTVN4item8ExampleAE) + 16;
    -[hidden]->
}

card "::item::ExampleB::__ct_comp() -> void" {
    -[hidden]->
}

card "::item::ExampleA::__ct_comp() -> void" {
    -[hidden]->
}


@enduml
