@startuml

class "::items::Abc3" as @26 {
}
class "::items::Abc2C" as @42 {
}
class "::items::Abc2B" as @69 {
}
class "::items::Abc2A" as @101 {
}
class "::items::Abc1<int, int>" as @64 {
    {field} + int fieldA
    {field} {static} + int fieldB
}
class "::items::Abc1<double, double>" as @65 {
    {field} + double fieldA
    {field} {static} + double fieldB
}
class "::items::Abc1<float, char>" as @97 {
    {field} + float fieldA
    {field} {static} + char fieldB
}
class "::items::Abc1<TTypeA, TTypeB>" as @127 <<T,#FF7700>> {
    {field} + TTypeA fieldA
    {field} + TTypeB fieldB
}
class "::items::Abc1<int, bool>" as @124 {
    {field} + int fieldA
    {field} {static} + bool fieldB
}
class "::items::Abc3::calc_templ" as @60

' ::items::Abc3 *--> ::items::Abc3::calc_templ
"@26" *--> "@60"
' ::items::Abc2C --|> ::items::Abc1<int, int>
"@42" --|> "@64": "pub"
' ::items::Abc2C --|> ::items::Abc1<double, double>
"@42" --|> "@65": "pub"
' ::items::Abc2B --|> ::items::Abc1<float, char>
"@69" --|> "@97": "pub"
' ::items::Abc2A --|> ::items::Abc1<int, bool>
"@101" --|> "@124": "pub"
' ::items::Abc1<int, int> ..> ::items::Abc1: spec.
"@64" ..> "@127": spec.
' ::items::Abc1<double, double> ..> ::items::Abc1: spec.
"@65" ..> "@127": spec.
' ::items::Abc1<float, char> ..> ::items::Abc1: spec.
"@97" ..> "@127": spec.
' ::items::Abc1<int, bool> ..> ::items::Abc1: spec.
"@124" ..> "@127": spec.

@enduml
