@startuml

class "::Duck" as item_0 {
    {field} + int noquacks
    {method} + void quack() 
}
class "::property::WalkingAnimal" as item_1 {
    {field} + __vtbl_ptr_type * _vptr.WalkingAnimal
    {field} + double walkdistance
    {method} + void walk(double const distance) 
}
class "::property::FlyingAnimal" as item_2 {
    {field} + __vtbl_ptr_type * _vptr.FlyingAnimal
    {field} + double flydistance
    {method} + void fly(double const distance) 
}
class "::property::Animal" as item_3 {
    {field} + int size
}

' ::Duck --|> ::property::FlyingAnimal
item_0 --|> item_2: "pub"
' ::Duck --|> ::property::WalkingAnimal
item_0 --|> item_1: "pub"
' ::property::WalkingAnimal --|> ::property::Animal
item_1 --|> item_3: "virt pub"
' ::property::FlyingAnimal --|> ::property::Animal
item_2 --|> item_3: "virt pub"

@enduml
