@startuml

class "::Duck" as @14 {
    {field} + int noquacks = 0
    {method} +  ~Duck() =default
    {method} +  Duck(::Duck & /*anonym*/) =default
    {method} +  Duck(::Duck const & /*anonym*/) =default
    {method} +  Duck() 
    {method} + void quack() 
}
class "::property::WalkingAnimal" as @26 {
    {field} + double walkdistance = 0.0
    {method} +  ~WalkingAnimal() =default
    {method} +  WalkingAnimal(::property::WalkingAnimal & /*anonym*/) =default
    {method} +  WalkingAnimal(::property::WalkingAnimal const & /*anonym*/) =default
    {method} +  WalkingAnimal() 
    {method} + void walk(double const distance) 
}
class "::property::FlyingAnimal" as @25 {
    {field} + double flydistance = 0.0
    {method} +  ~FlyingAnimal() =default
    {method} +  FlyingAnimal(::property::FlyingAnimal & /*anonym*/) =default
    {method} +  FlyingAnimal(::property::FlyingAnimal const & /*anonym*/) =default
    {method} +  FlyingAnimal() 
    {method} + void fly(double const distance) 
}
class "::property::Animal" as @43 {
    {field} + double weight
    {field} + double width
    {field} + double height
    {method} +  ~Animal() =default
    {method} +  Animal(::property::Animal & /*anonym*/) =default
    {method} +  Animal(::property::Animal const & /*anonym*/) =default
    {method} +  Animal() =default
}

' ::Duck --|> ::property::FlyingAnimal
"@14" --|> "@25": "pub"
' ::Duck --|> ::property::WalkingAnimal
"@14" --|> "@26": "pub"
' ::property::WalkingAnimal --|> ::property::Animal
"@26" --|> "@43": "pub"
' ::property::FlyingAnimal --|> ::property::Animal
"@25" --|> "@43": "pub"

@enduml
