@startuml

class "::Duck" as item_0 {
    {field} + int noquacks = 0
    {method} +  ~Duck() =default
    {method} +  Duck(::Duck & /*anonym*/) =default
    {method} +  Duck(::Duck const & /*anonym*/) =default
    {method} +  Duck() 
    {method} + void quack() 
}
class "::property::WalkingAnimal" as item_1 {
    {field} + double walkdistance = 0.0
    {method} +  ~WalkingAnimal() =default
    {method} +  WalkingAnimal(::property::WalkingAnimal & /*anonym*/) =default
    {method} +  WalkingAnimal(::property::WalkingAnimal const & /*anonym*/) =default
    {method} +  WalkingAnimal() 
    {method} + void walk(double const distance) 
}
class "::property::FlyingAnimal" as item_2 {
    {field} + double flydistance = 0.0
    {method} +  ~FlyingAnimal() =default
    {method} +  FlyingAnimal(::property::FlyingAnimal & /*anonym*/) =default
    {method} +  FlyingAnimal(::property::FlyingAnimal const & /*anonym*/) =default
    {method} +  FlyingAnimal() 
    {method} + void fly(double const distance) 
}
class "::property::Animal" as item_3 {
    {field} + double weight
    {field} + double width
    {field} + double height
    {method} +  ~Animal() =default
    {method} +  Animal(::property::Animal & /*anonym*/) =default
    {method} +  Animal(::property::Animal const & /*anonym*/) =default
    {method} +  Animal() =default
}

' ::Duck --|> ::property::FlyingAnimal
item_0 --|> item_2: "pub"
' ::Duck --|> ::property::WalkingAnimal
item_0 --|> item_1: "pub"
' ::property::WalkingAnimal --|> ::property::Animal
item_1 --|> item_3: "pub"
' ::property::FlyingAnimal --|> ::property::Animal
item_2 --|> item_3: "pub"

@enduml
